// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_name = 1;</code>
   */
  java.lang.String getEventName();
  /**
   * <code>string event_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventNameBytes();
}
