// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface GetEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.GetEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_name = 1;</code>
   */
  java.lang.String getEventName();
  /**
   * <code>string event_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <code>string phone_number = 2;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 2;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
