// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public final class Greeting {
  private Greeting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_RegisterAppRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_RegisterAppRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_RegisterAppResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_RegisterAppResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_ListenMimicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_ListenMimicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_ListenMimicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_ListenMimicResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicRecieveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicRecieveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicRecieveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicRecieveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicRecieveResponse_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicRecieveResponse_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicSendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicSendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicSendRequest_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicSendRequest_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicSendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicSendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_HealthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_HealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_HealthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_HealthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_EventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_EventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicStartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicStartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_ServerStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_ServerStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicLayoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicLayoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_MimicLayoutRequest_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_MimicLayoutRequest_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_GetEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_GetEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_GetEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_GetEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_InitiateMimicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_InitiateMimicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_event_InitiateMimicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_event_InitiateMimicResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016greeting.proto\022\013proto.event\"\'\n\022Registe" +
      "rAppRequest\022\021\n\tuser_code\030\001 \001(\t\"#\n\023Regist" +
      "erAppResponse\022\014\n\004uuid\030\001 \001(\t\"\"\n\022ListenMim" +
      "icRequest\022\014\n\004uuid\030\001 \001(\t\"%\n\023ListenMimicRe" +
      "sponse\022\016\n\006action\030\001 \001(\t\"#\n\023MimicRecieveRe" +
      "quest\022\014\n\004uuid\030\001 \001(\t\"\221\001\n\024MimicRecieveResp" +
      "onse\022\021\n\tlayout_id\030\001 \001(\005\0229\n\004data\030\002 \003(\0132+." +
      "proto.event.MimicRecieveResponse.DataEnt" +
      "ry\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"\227\001\n\020MimicSendRequest\022\014\n\004uuid\030\001 \001" +
      "(\t\022\021\n\tlayout_id\030\002 \001(\005\0225\n\004data\030\003 \003(\0132\'.pr" +
      "oto.event.MimicSendRequest.DataEntry\032+\n\t" +
      "DataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"%\n\021MimicSendResponse\022\020\n\010response\030\001 \001(\t" +
      "\"\035\n\rHealthRequest\022\014\n\004ping\030\001 \001(\t\"\036\n\016Healt" +
      "hResponse\022\014\n\004pong\030\001 \001(\t\"\"\n\014EventRequest\022" +
      "\022\n\nevent_name\030\001 \001(\t\"!\n\rEventResponse\022\020\n\010" +
      "response\030\001 \001(\t\"!\n\021MimicStartRequest\022\014\n\004u" +
      "uid\030\001 \001(\t\"%\n\023ServerStreamRequest\022\016\n\006app_" +
      "id\030\001 \001(\t\" \n\rMimicResponse\022\017\n\007request\030\001 \001" +
      "(\t\"\215\001\n\022MimicLayoutRequest\022\021\n\tlayout_id\030\001" +
      " \001(\005\0227\n\004data\030\002 \003(\0132).proto.event.MimicLa" +
      "youtRequest.DataEntry\032+\n\tDataEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"%\n\017GetEventRe" +
      "quest\022\022\n\nevent_name\030\001 \001(\t\"<\n\020GetEventRes" +
      "ponse\022\022\n\nevent_name\030\001 \001(\t\022\024\n\014phone_numbe" +
      "r\030\002 \001(\t\":\n\024InitiateMimicRequest\022\021\n\tfrom_" +
      "code\030\001 \001(\t\022\017\n\007to_code\030\002 \001(\t\")\n\025InitiateM" +
      "imicResponse\022\020\n\010response\030\001 \001(\t2\234\005\n\014Event" +
      "Service\022H\n\013HealthCheck\022\032.proto.event.Hea" +
      "lthRequest\032\033.proto.event.HealthResponse\"" +
      "\000\022G\n\014CaptureEvent\022\031.proto.event.EventReq" +
      "uest\032\032.proto.event.EventResponse\"\000\022L\n\tGe" +
      "tEvents\022\034.proto.event.GetEventRequest\032\035." +
      "proto.event.GetEventResponse\"\0000\001\022R\n\013Regi" +
      "sterApp\022\037.proto.event.RegisterAppRequest" +
      "\032 .proto.event.RegisterAppResponse\"\000\022V\n\r" +
      "MimicListener\022\037.proto.event.ListenMimicR" +
      "equest\032 .proto.event.ListenMimicResponse" +
      "\"\0000\001\022W\n\014MimicRecieve\022 .proto.event.Mimic" +
      "RecieveRequest\032!.proto.event.MimicReciev" +
      "eResponse\"\0000\001\022L\n\tMimicSend\022\035.proto.event" +
      ".MimicSendRequest\032\036.proto.event.MimicSen" +
      "dResponse\"\000\022X\n\rInitiateMimic\022!.proto.eve" +
      "nt.InitiateMimicRequest\032\".proto.event.In" +
      "itiateMimicResponse\"\000B*\n\031com.wheelseye.p" +
      "roto.eventP\001Z\013proto/eventb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_event_RegisterAppRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_event_RegisterAppRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_RegisterAppRequest_descriptor,
        new java.lang.String[] { "UserCode", });
    internal_static_proto_event_RegisterAppResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_event_RegisterAppResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_RegisterAppResponse_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_proto_event_ListenMimicRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_event_ListenMimicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_ListenMimicRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_proto_event_ListenMimicResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_event_ListenMimicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_ListenMimicResponse_descriptor,
        new java.lang.String[] { "Action", });
    internal_static_proto_event_MimicRecieveRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_event_MimicRecieveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicRecieveRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_proto_event_MimicRecieveResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_event_MimicRecieveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicRecieveResponse_descriptor,
        new java.lang.String[] { "LayoutId", "Data", });
    internal_static_proto_event_MimicRecieveResponse_DataEntry_descriptor =
      internal_static_proto_event_MimicRecieveResponse_descriptor.getNestedTypes().get(0);
    internal_static_proto_event_MimicRecieveResponse_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicRecieveResponse_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_event_MimicSendRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_event_MimicSendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicSendRequest_descriptor,
        new java.lang.String[] { "Uuid", "LayoutId", "Data", });
    internal_static_proto_event_MimicSendRequest_DataEntry_descriptor =
      internal_static_proto_event_MimicSendRequest_descriptor.getNestedTypes().get(0);
    internal_static_proto_event_MimicSendRequest_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicSendRequest_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_event_MimicSendResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_event_MimicSendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicSendResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_proto_event_HealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_event_HealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_HealthRequest_descriptor,
        new java.lang.String[] { "Ping", });
    internal_static_proto_event_HealthResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_event_HealthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_HealthResponse_descriptor,
        new java.lang.String[] { "Pong", });
    internal_static_proto_event_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_event_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_EventRequest_descriptor,
        new java.lang.String[] { "EventName", });
    internal_static_proto_event_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_proto_event_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_EventResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_proto_event_MimicStartRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_proto_event_MimicStartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicStartRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_proto_event_ServerStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_proto_event_ServerStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_ServerStreamRequest_descriptor,
        new java.lang.String[] { "AppId", });
    internal_static_proto_event_MimicResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_proto_event_MimicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicResponse_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_proto_event_MimicLayoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_proto_event_MimicLayoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicLayoutRequest_descriptor,
        new java.lang.String[] { "LayoutId", "Data", });
    internal_static_proto_event_MimicLayoutRequest_DataEntry_descriptor =
      internal_static_proto_event_MimicLayoutRequest_descriptor.getNestedTypes().get(0);
    internal_static_proto_event_MimicLayoutRequest_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_MimicLayoutRequest_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_proto_event_GetEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_proto_event_GetEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_GetEventRequest_descriptor,
        new java.lang.String[] { "EventName", });
    internal_static_proto_event_GetEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_proto_event_GetEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_GetEventResponse_descriptor,
        new java.lang.String[] { "EventName", "PhoneNumber", });
    internal_static_proto_event_InitiateMimicRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_proto_event_InitiateMimicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_InitiateMimicRequest_descriptor,
        new java.lang.String[] { "FromCode", "ToCode", });
    internal_static_proto_event_InitiateMimicResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_proto_event_InitiateMimicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_event_InitiateMimicResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
