// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface HealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.HealthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ping = 1;</code>
   */
  java.lang.String getPing();
  /**
   * <code>string ping = 1;</code>
   */
  com.google.protobuf.ByteString
      getPingBytes();
}
