// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface HealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.HealthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pong = 1;</code>
   */
  java.lang.String getPong();
  /**
   * <code>string pong = 1;</code>
   */
  com.google.protobuf.ByteString
      getPongBytes();
}
