// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface InitiateMimicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.InitiateMimicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from_code = 1;</code>
   */
  java.lang.String getFromCode();
  /**
   * <code>string from_code = 1;</code>
   */
  com.google.protobuf.ByteString
      getFromCodeBytes();

  /**
   * <code>string to_code = 2;</code>
   */
  java.lang.String getToCode();
  /**
   * <code>string to_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getToCodeBytes();
}
