// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface ListenMimicResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.ListenMimicResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string action = 1;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 1;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();
}
