// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface RegisterAppResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.RegisterAppResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
