// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface RegisterAppRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.RegisterAppRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_code = 1;</code>
   */
  java.lang.String getUserCode();
  /**
   * <code>string user_code = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserCodeBytes();
}
