// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.wheelseye.proto.event;

public interface ServerStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.event.ServerStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string app_id = 1;</code>
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppIdBytes();
}
